### ISSUE TITLE
Sprockets-required files don't share their required modules

### ISSUE THREAD

**Issue by mattwondra** [browserify-rails/browserify-rails#18]
It appears that when you use `//= require` to include browserify-able files, these files don't share their modules. For example:

```
//= require modules/a
//= require modules/b
// Both modules have: var x = require("../lib/counter");
```

In the compiled file, the `counter` library will be written twice. I know there are [documented ways around this](https://github.com/browserify-rails/browserify-rails#multiple-bundles) but it seems a huge burden to rely on this YAML file, especially in a large project with many files and multiple shared dependencies. 

The problem I've seen reported is mostly to do with file bloat — you don't want large libraries to be defined multiple times in one file. But in some cases, it's actually catastrophic to initialize the same library several times on the same page. For example, React will refuse to work unless it's give a solitary definition/initialization.

I built a reduced test case and documented the issue here: https://github.com/mattwondra/browserify-rails-issue

Ideally, the postprocessor in this gem should be able to share the module definitions across `//= require`-d files. But if this is overly difficult or impossible given the Asset Pipeline's tools, may I suggest an optional `strict_mode` config flag that prevents you from `//= require`-ing Browserify-able files?

I built a local prototype and would be happy to submit a pull request. When this mode is set, the asset precompile fails if it detects that a `//= require`-d file needs to be Browserified. The error message tells you to `require(...)` them instead.

Thanks for the consideration!

**Comment by schovi** [comment]
Any progress with that? I am new with this gem and npm generally and this problem blowing my mind. I am using this for `require('react-flux')` and when it is loaded twice or three times it is broken, because there are 3 different instances of this library and they do not communicate (my explanation).

browserify.yml should somehow solve that, but i really dont know how. I require react-flux in these files `assets/javascripts/app.js`, `assets/javascripts/actions/user.js`, `assets/javascripts/constants/user.js` and `assets/javascripts/stores/user.js`

Or is there any better solution? Thanks

**Comment by cymen** [comment]
@schovi There is a lot going on -- I started to type a reply and decided instead to create an example repo for using multiple bundles:

https://github.com/browserify-rails/multiple-bundles-example

Can you take a look at that and let me know if that makes it all mesh together?

**Comment by cymen** [comment]
@schovi I should mention, `react-flux` is your `./robot` in the example. That way you can have `react-flux` in one bundle and the other bundles can be marked as having it `external` so you'll only have one copy of it packaged up (but you'll have to ensure you load that bundle that does have `react-flux` marked as `require` before any other bundle with a javascript tag so in the HTML page).

Also note the issue with being stuck at browserify v4.x at the bottom of the README (at example repo)!

**Comment by rtorr** [comment]
@schovi We ended up not using browserify-rails and are using browserify directly. 

To sum it up.
```
/* application.js */
// require "_bundle.js"
```

```
/* bundle.js */
require('whatever');
```

we have `bundle.js` transformed with browserify into `_bundle.js`

`_bundle.js` is gitignored.

`package.json` example

```{
  "name": "example",
  "scripts": {
    "build-js": "browserify ./app/assets/javascripts/bundle.js -o ./app/assets/javascripts/_bundle.js",
    "watch-js": "watchify ./app/assets/javascripts/bundle.js -o ./app/assets/javascripts/_bundle.js",
  },
  "browserify": {
    "transform": [
      [
        "reactify",
        {
          "ext": ".js"
        }
      ]
    ]
  },
  "dependencies": {
    "react": "^0.12.1",
    "react-router": "^0.11.6",
    "react-tools": "^0.12.1",
    ...
  },
  "devDependencies": {
    "browserify": "^5.11.0",
    "reactify": "^0.17.1",
    "watchify": "^1.0.2",
    ...
  },
...
}
```
you can run `npm run watch-js`

We have something a little bit more complex than this example, but this could get you started.

**Comment by schovi** [comment]
@cymen It seems to work, but

1) In my app i have lot of dependencies. Only for react-flux it is 3 times per model (it has some structure) and i will have approx 10 models. So it is 30 files. Plus other libraries. It is not maintanable with this solution.

2) This solution is not production ready. Separate files wont compile into one :/

I guess i will try to beat that Webpack solution linked there.

**Comment by cymen** [comment]
@schovi 
1) We are using browserify and browserify-rails does no more than browserify itself would do. If your issue is with having to deal with browserify.yml due to wanting to have tons of bundles and having to mark shared modules as external, then yes -- it'll be annoying to maintain.

2) We are using the Rails asset pipeline. All you have to do is `bundle exec rails assets:precompile` and away you go -- that is the Rails way to get your one file.

The sweet spot for this gem is for projects:

* using the Rails asset pipeline (ie have engineers that don't want to go compile JS separately)
* want one big JavaScript bundle
* or those with multiple big JS bundles that are refactoring to one

Once you get into wanting to share a log of modules, it gets more complicated. It isn't an exceedingly hard problem to fix but it needs someone to put in the time and in some cases some of the above sweet spots don't apply and other approaches make more sense.

If you are indeed compiling to one file you don't need to do `require`/`external` at all -- this project will work just fine for you.
