### ISSUE TITLE
Encoding::UndefinedConversionError occurs  when js file contains Chinese characters

### ISSUE THREAD

**Issue by GreatVincy** [browserify-rails/browserify-rails#209]
I use browserify-rails on Rails 5.1.4,but an error named **Encoding::UndefinedConversionError in MyController#my_action**  occured.
I guess it‘s because my application.js contains Chinese chardacters.
All my js and erb files are encoded using UTF-8.
How should I deal with the problem?

+ error info:
> **Encoding::UndefinedConversionError in PositionDecisions#index**
>Showing /Users/rong/Desktop/clue-platform/app/views/layouts/application.html.erb where line #15 raised:
> "\xE9" from ASCII-8BIT to UTF-8
> Extracted source (around line #15):
>     <%= javascript_include_tag "application" ,"data-turbolinks-track" => "reload" %>
> Rails.root: /Users/rong/Desktop/clue-platform

+ environments:
> ruby 2.4.1p111
> rails 5.1.4
> sprockets 4.0.0.beta5
> browserify-rails 4.2.0
> node 8.5.0
> Mac OS Sierra 10.12.6

thanks!

**Comment by cymen** [comment]
I tried adding a basic test in the `./test/dummy` app with a JavaScript file that has some UTF-8 in it and it came through without an issue. The dummy app uses an older version of Rails though.

So I don't know what the problem is.

Have you thought about using this:

https://github.com/rails/webpacker

Unless you have legacy JavaScript, I'd recommend the above for new projects.

**Comment by GreatVincy** [comment]
Thanks, my rails project is now integrated with webpack and runing well.
