### ISSUE TITLE
Adding support for browserify-incremental

### ISSUE THREAD

**Issue by gabrielecirulli** [browserify-rails/browserify-rails#31]
[Browserify-incremental](https://www.npmjs.com/package/browserify-incremental) seems like an interesting tool to speed up browserify builds (other than solving #30), so I'm wondering if it would make sense (and you like the idea) to support it.

If so, I can also try to spend some time on this and make a pull request to attempt it.

**Comment by cymen** [comment]
@gabrielecirulli I figured out our issue was related to a bug in some i18n node modules. Or some oddity in the way they interact. I had to do this in my package.json:

```json
-    "handlebars-intl": "^1.0.0",
+    "handlebars-intl": "1.0.0",
     "hbsfy": "^2.2.0",
-    "intl": "^0.1.4",
-    "intl-messageformat": "^1.0.1",
+    "intl": "0.1.4",
+    "intl-messageformat": "1.0.1",
```
As one ore more minor + versions on those modules caused issues. So that is great news -- it wasn't browserify-incremental.

I also found this list of transforms: https://github.com/substack/node-browserify/wiki/list-of-transforms

I want to look into some of them more to see if I can get some more performance out of browserify. But the good news is I figured out our slow page loads are not browserify -- the bundle actually gets made relatively quickly. But code from other parts of the site is using sprockets and loading file by file (to the browser in development mode) and this is causing a major slowdown as the amount of JavaScript there has increased.

**Comment by cymen** [comment]
I would also be interested in two other things:

1) Being able to whitelist certain directories for browserify and not having it run on others (node_modules would be special case of course).

2) Being able to have more control over what does and does not get source maps generated. I don't know if this is possible but it would be great not to have source maps for things outside of my code -- sometimes they are useful but if we can get faster performance, I'd be happy to toggle on "source map everything" when needed but otherwise have only my code be source mapped.

**Comment by cymen** [comment]
We could probably start another issue focused on performance and close this (now that browserify-incremental is merged)  -- might make it easier to find.

**Comment by gabrielecirulli** [comment]
Thanks for finding the solution to that problem! Things are looking great :smile: I would definitely love to open an issue to discuss performance.

What did you mean exactly when you said sprockets is loading code file by file? Is this something happening in the server or do you mean that multiple script tags are being passed on to the browser?

Regarding your points:
 1. I would love that. In fact, I had a problem with 6to5 running on my `vendor/assets/javascripts/*`, which it shouldn't since most of the libraries found there aren't meant to be transformed. I resorted to telling 6to5 to ignore it, but it felt like a slight hack. It would be more interesting to be able to do this at the "root", through browserify-rails.

 2. No idea about that one in particular. I'm not even too sure how source maps are working in my current workflow, since I have 6to5 generating source maps (since it also deals with jsx files) and browserify seemingly just concatenating them. Anyway, maybe there's an option for it in browserify, but I have never had a proper look at it.

**Comment by cymen** [comment]
Closing as I think we are good on this (although the sprockets changes with browserify-rails 2.x might make this no longer needed -- it would be interesting to know).
