### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by brandonparsons** [browserify-rails/browserify-rails#37]
Hi there,

This is more of a request for clarification than a question. I'm brand new to Browserify and generally have no idea what I am doing :)

1. Can I `require("foo")` in multiple locations, and `browserify-rails` will only include `foo` once?
1. If 1 == "Yes", does it matter where the `require("foo")` happens? (i.e. does it make a difference if it is inside or outside of a function?)
2. If I am mixing & matching modules and standard Rails javascript organization, can I `require("bar")` in one location, and then `//= require bar` in another, and I will only get the package once?

Thanks!

**Comment by cymen** [comment]
This is the way I think about it. Say I have this file:

* application.js

And within application.js, I have a few `//= require something` which is the sprockets require and then I have below some CommonJS (ie `module.exports` or `require`). What will happen is this:

1) I include application.js with some Rails helper in a view to pull it into the page.
2) My browser requests .../application.js.
3) Rails finds that file and the Rails asset pipeline opens up the file and looks inside of it.
4) The asset pipeline resolves the sprocket requires and then browserify-rails sees the CommonJS usage and kicks off the "run browserify on this"... And then everything gets browserified all the way down.

Where does it get complicated?

Say I have:

* application.js
* someOther.js

If I include both in my HTML via on the Rails side with a script tag helper, my browser will do two requests -- one for each file. Say both application.js AND someOther.js have a `require("foo")` -- unless you explicitly tell browserify-rails that one file should include that module and another should treat it as external, the module will get bundled separately into each .js file. As you can guess, this can create reference problems (as in, I could make a module that is `module.exports = {}` which would let me share the reference to that anonymous object -- but if that is bundled separately, the references point to different objects so the shared state is not shared).

To keep it simple, I recommend having one entry point to browserify -- in other words, try to structure your JavaScript so that you do not need to use bundling and instead you have say application.js which introduces the CommonJS requires and then all the code below that is pulled in there. That does not work for every project. To understand multiple bundles, read this:

https://github.com/substack/node-browserify#multiple-bundles

But the simple picture is:

Rails |-| asset pipeline |-| let sprockets do its thing or whatever is before browserify-rails |-| browserify all the way down

**Comment by cymen** [comment]
Please ask more questions -- I am crunched for time and feel my explanation above is not 100% clear but I am more than happy to answer as much as I can.

**Comment by brandonparsons** [comment]
Thank you for that.  All of this packaging is blowing my mind :)

It is ok though to `require('foo')` in multiple files that are only loaded via browserify right? i.e. if I follow the advice above, and only load the single JS file into Rails, it doesn't matter what I do in my module files - I won't get 8 copies of `lodash` in my browser javascript?

**Comment by cymen** [comment]
Correct -- try it and take a look at the output. Just load the file in your browser so maybe http://localhost:3000/application.js or whatever the URL is. It looks odd but you'll see a pattern. You could also make a module and put a known string in it -- say "abc123hahah" and then require it in a bunch of places. Then search for the string in application.js and see how it is only there once no matter how many times you require it.

**Comment by cymen** [comment]
Closing with assumption this is making sense. Please reopen if any further questions.

**Comment by brandonparsons** [comment]
Thanks @cymen  - appreciate your time :)
