### ISSUE TITLE
I'm no longer actively working on browserify-rails (as much as before) -- it would be great to have more contributors

### ISSUE THREAD

**Issue by cymen** [browserify-rails/browserify-rails#85]
A couple months ago I switched employers. Part of the change is I was able to get out of working within the Rails asset pipeline. So I don't use this gem anymore day to day. I see a lot of requests for things but I do not want to spend my personal time working on this gem -- I'd much rather work on other projects.

If you are starting a project from scratch, I urge you to not use the Rails asset pipeline for JavaScript. It is like being in the stone age of JavaScript (no modules, lots of jQuery, globals all over the place, no unit tests, etc). In my opinion and experience, the Rails asset pipeline + JavaScript === you are going to be in a world of pain. This gem makes things a little bit better. But it is like a band aid: you really need to cut that arm off. That is part of why I have lost interest in this gem -- I do not anticipate ever working on another Rails project that uses the Rails asset pipeline for JavaScript development.

If you are interested in contributing to this gem, it would be great to have more contributors who have merge and release access. So please speak up.

**Comment by gabrielecirulli** [comment]
I would be interested of being added as a contributor, mainly because we actively use this gem in our project and there are sporadic situations where we might need changes. I don't foresee being truly actively involved in the resolution of bugs/issues with the gem directly except for specific situations, also because of lack of time. Let me know if this could still be interesting.

**Comment by gabrielecirulli** [comment]
As an example, yesterday I discovered a potential pitfall in how the transform options from `package.json` at the root of a project aren't really passed to browserify when it comes to transforming the root JavaScript file, so I came here wondering if there was anything that could be done about it and ended up seeing this issue.

**Comment by cymen** [comment]
@gabrielecirulli I sent you an invite. I understand regarding time. I hope to try to fix some things when I have time too so I'll stick around I just hope to get more people who are actively using this involved.

**Comment by gabrielecirulli** [comment]
Thanks. On a slightly related note I also noticed that [Babel](babeljs.io) now supports [ES6 modules](http://www.2ality.com/2014/09/es6-modules-final.html), but the `commonjs_module?` method in `BrowserifyProcessor` only checks for `require` within the file. In my application file, which I converted recently to ES6 modules, it was working basically by accident because I mentioned the word "require" in a comment :stuck_out_tongue:. Would it make sense to make this method aware of ES6 modules? It'd basically also search for the words "import" and "export".

**Comment by cymen** [comment]
I was wondering about the same thing -- I do think it would make sense to have it detect ES6 modules.

**Comment by gabrielecirulli** [comment]
Cool, I could attempt that soon and make a PR.

**Comment by cymen** [comment]
I updated the title to include "as much as before" to be more accurate. I think I figured out a way to go forward on the gem incompatibilities. It was getting frustrating and I didn't have as much time as I'd like to devote to it. I still hope other people who are using this can take the time to contribute because having active users contribute is a huge win. But I'll keep going too when I have time.

**Comment by cymen** [comment]
@gabrielecirulli I forgot to add you as a gem owner too (on rubygems). I just fixed that.

**Comment by gabrielecirulli** [comment]
Great to know! Thank you!
