### ISSUE TITLE
Sources maps not working on production

### ISSUE THREAD

**Issue by orlando** [browserify-rails/browserify-rails#99]
I'm trying to get sources maps to work on production, but after compiling the files, no `sourceMappingURL` is present in the file.

Here's my browserify config

```ruby
config.browserify_rails.commandline_options = ['-t pkgify']
config.browserify_rails.source_map_environments += ['development', 'production', 'staging']
config.browserify_rails.use_exorcist = true
```

When I do it in development it works, but other than that, source maps are missing.

Any idea what could be wrong?

Thanks!

**Comment by cymen** [comment]
@dan-brewster do you have any ideas on how to debug this?

**Comment by dan-brewster** [comment]
This is a really tricky issue, I had a lot of issues around this as well. A few things to try: (1) Make sure that if you're using uglifier, it doesn't remove comments with "sourceMappingUrl" in them. (2) You may have some loading issues because semi-colons aren't inserted between files -- we were finding that semi-colons were inserted after the last character of a file, putting them inside the sourceMappingUrl comment. We ended up monkeypatching sprockets to insert a newline before each semi-colon to fix it.

If that isn't fixing it, one thing to try is to remove all the extra steps, and just have browserify-rails do as little as possible, and see if that exposes the issue. Did you have success if you didn't use exorcist?

Sorry for the delayed response; because of some unrelated issues we did end up moving to a gulp.js-based pipline for our javascript (so we're using gulp and sprockets for different files in the same project) and that has worked surprisingly well. Not sure if you're able to do it, but it may be something to consider if you can. It was less work for us than continuing to fuss with monkeypatches and weird issues.

**Comment by cymen** [comment]
@dan-brewster Thanks -- I think that last point is worth paying particular attention to. I actively contributed to this project because I had a legacy JavaScript codebase on Rails. So I used this to convert all of the code to CommonJS. Once that is done, it opens up the door to a lot of other approaches to building the JavaScript.

So at a meta-level, I think browserify-rails is great for simple projects or legacy codebases that are on Rails and want to switch to CommonJS. Once you want anything with any complexity, it's easier to move on to something else as the sweet spot just isn't here.

Of course, PRs are welcome and all that but hopefully the Rails asset pipeline will one day support CommonJS itself and this project will be deprecated.

**Comment by orlando** [comment]
@dan-brewster that's exactly what I ended up doing (move to gulp using https://github.com/vigetlabs/gulp-rails-pipeline as an example).

I'm not working with browserify-rails anymore, should we close this issue? (maybe this issue was specific to my application).

Thanks!

**Comment by cymen** [comment]
I'll close -- it's good to know it's an issue though. Thanks!
